# Generated by Django 2.1.7 on 2019-04-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190319_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='about',
            field=models.TextField(default='I am a default descripition'),
            preserve_default=False,
        ),
    ]
