# Generated by Django 2.1.7 on 2019-04-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_attorney_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='about',
        ),
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
