# Generated by Django 2.1.7 on 2019-03-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseType1', models.CharField(max_length=250)),
                ('caseType2', models.CharField(max_length=250)),
                ('caseType3', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
