# Generated by Django 2.1.7 on 2019-03-18 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='attorney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Attorney'),
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
