# Generated by Django 2.1.7 on 2019-03-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190316_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
