# Generated by Django 2.1.7 on 2019-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('counterBid', models.BooleanField()),
                ('bidAccepted', models.BooleanField(null=True)),
            ],
        ),
    ]
