# Generated by Django 2.1.7 on 2019-04-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20190419_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='counterBid',
            field=models.BooleanField(null=True),
        ),
    ]
